### ISSUE TITLE
outgoing RTP payload(s) configuration

### ISSUE THREAD

**Issue by philn** [ystreet/gst-plugins-bad#4]
Currently the SDP generated depends on the payloaders linked to webrtcbin.

It would be great if webrtcbin can use the payloaders found in the registry during negotiation instead of depending on those linked to the bin. Then the bin could emit a signal, notifying application side which payloaders are required after the negotiation was completed.

Perhaps it would also be good to have a white-list of payloader formats supplied as in a property of the bin? Just some ideas anyway.

**Comment by ystreet** [comment]
Right, so this problem is semi-neatly solved by exposing transceivers and the associated codec preferences.

As for whether payloaders should be inside webrtcbin Im going to say no for now.  It's entirely possible (and in-use) to pass pre-payloaded rtp streams into webrtcbin without encoding effectively creating a relay.

**Comment by philn** [comment]
Exposing transceivers and codec prefs would indeed be an interesting approach to try out!

I'm not suggesting payloaders should be inside the bin though. For now I suppose I'll try to connect some payloaders beforehand but I think I would still need some kind of notification about the selected outgoing format, if the transceivers are not exposed yet.
